---
# This Playbook is used
# for testing sclorg-testing-farm

- name: Testing sclorg-testing-farm repo is everything is present in host provided by Testing Farm
  hosts: "{{ hosts | default('localhost') }}"
  vars:
    os_test: "{{ lookup('env', 'OS') }}"
    package_names_all:
      - git
      - make
      - ansible
    package_names_centos7:
      - perl
      - centos-release-scl-rh
      - rsync
      - groff-base
      - centos-release-openshift-origin
      - epel-release
      - rh-python36-python-virtualenv
      - origin-clients
      - python3
      - golang-github-cpuguy83-go-md2man
      - mailx
      - docker
      - docker-client
      - docker-common
    package_names_c8s:
      - podman-docker
      - podman
      - libseccomp-devel
      - golang-github-cpuguy83-md2man
      - mailx
    package_names_c9s:
      - podman-docker
      - podman
      - golang-github-cpuguy83-md2man
      - s-nail
    package_names_fedora:
      - podman-docker
      - podman
      - acl
      - libseccomp-devel
      - openssl
      - python3-pip
      - golang-github-cpuguy83-md2man
      - s-nail
    files_to_check_fedora:
      - /etc/containers/nodocker
    files_to_check_centos7:
      - /etc/rhsm/ca/redhat-uep.pem
    files_to_check_c8s:
      - /etc/containers/nodocker
    files_to_check_c9s:
      - /etc/containers/nodocker


  tasks:
    - debug: msg="{{ os_test }}"
    - block:
        - name: Check if listed package is installed on CentOS 7
          include_tasks: ./tasks/check_rpm_presents.yml
          loop: "{{ package_names_all + package_names_centos7 }}"
        - name: Check if files are present on CentOS 7
          include_tasks: ./tasks/check_file_presents.yml
          loop: "{{ files_to_check_centos7 }}"
      when: (os_test is defined) and (os_test == "centos7")

    - block:
        - name: Check if listed package is installed on CentOS Stream 8
          include_tasks: ./tasks/check_rpm_presents.yml
          loop: "{{ package_names_all + package_names_c8s }}"
        - name: Check if files are present on CentOS Stream 8
          include_tasks: ./tasks/check_file_presents.yml
          loop: "{{ files_to_check_c8s }}"
      when: (os_test is defined) and (os_test == "c8s")

    - block:
        - name: Check if listed package is installed on CentOS Stream 9
          include_tasks: ./tasks/check_rpm_presents.yml
          loop: "{{ package_names_all + package_names_c9s }}"
        - name: Check if files are present on CentOS Stream 9
          include_tasks: ./tasks/check_file_presents.yml
          loop: "{{ files_to_check_c9s }}"
      when: (os_test is defined) and (os_test == "c9s")

    - block:
        - name: Check if listed package is installed on Fedora
          include_tasks: ./tasks/check_rpm_presents.yml
          loop: "{{ package_names_all + package_names_fedora }}"

        - name: Check if file {{ item }} exists
          include_tasks: ./tasks/check_file_presents.yml
          loop: "{{ files_to_check_fedora }}"
      when: (os_test is defined) and (os_test == "fedora")
