---
- name: Add relay host
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^relayhost = '
    line: "relayhost = [smtp.corp.redhat.com]"

- name: Run the postfix service
  service: state=started name="{{ item }}" enabled=yes
  with_items:
    - postfix
